dynamicCSS:
    pattern:  /dynamic/css/{key}
    defaults: { _controller: CympelAnalyticsBundle:Default:dynamicCSS }
dynamicCSSImageFile:
    pattern: /dynamic/css/image/file/{key}/{domIdValue}
    defaults: { _controller: CympelAnalyticsBundle:Default:dynamicCSSImageFile }