dynamicCSS:
    pattern:  /dynamic/css/{key}
    defaults: { _controller: CympelAnalyticsBundle:DynamicCSS:dynamicCSS }
dynamicCSSImageFile:
    pattern: /dynamic/css/image/file/{key}/{domIdValue}
    defaults: { _controller: CympelAnalyticsBundle:DynamicCSS:dynamicCSSImageFile }
dynamicCSSTest:
    pattern: /dynamic/test
    defaults: { _controller: CympelAnalyticsBundle:Test:dynamicCSSTest }
dynamicJS:
    pattern:  /dynamic/js/{key}
    defaults: { _controller: CympelAnalyticsBundle:DynamicJS:dynamicJS }
dynamicJSCallbackShortUrl:
    pattern: /djsc/{key}/s/{selectorKey}/e/{eventKey}
    defaults: { _controller: CympelAnalyticsBundle:DynamicJS:dynamicJS }
dynamicJSCallback:
    pattern: /dynamic/js/callback/{key}/selector/{selectorKey}/event/{eventKey}
    defaults: { _controller: CympelAnalyticsBundle:DynamicJS:dynamicJSCallback }
dynamicJSTest:
    pattern: /dynamic/jsTest
    defaults: { _controller: CympelAnalyticsBundle:Test:dynamicJSTest }