parameters:
    cympelAnalytics.routeTrafficPersister.class: Cympel\Bundle\AnalyticsBundle\Services\RouteTrafficPersister
    cympel_analytics.dynamic_css_manager.class: Cympel\Bundle\AnalyticsBundle\Services\DynamicCSSManager
    cympel_analytics.dynamic_css_dom_id_manager.class: Cympel\Bundle\AnalyticsBundle\Services\DynamicCSSDomIdManager
    cympel_analytics.entity_manager:

services:
    cympelAnalytics.routeTrafficPersister:
        class: %cympelAnalytics.routeTrafficPersister.class%
        arguments: [@doctrine, "%cympel_analytics.entity_manager%"]
    cympel_analytics.dynamic_css_manager:
        class: %cympel_analytics.dynamic_css_manager.class%
        arguments: ["@doctrine", "@router", "@cympel_analytics.dynamic_css_dom_id_manager", "%cympel_analytics.entity_manager%"]
    cympel_analytics.dynamic_css_dom_id_manager:
        class: %cympel_analytics.dynamic_css_dom_id_manager.class%
        arguments: ["@doctrine", "@validator", "%cympel_analytics.entity_manager%"]