parameters:
    cympelAnalytics.routeTrafficPersister.class: Cympel\Bundle\AnalyticsBundle\Services\RouteTrafficPersister

services:
    cympelAnalytics.routeTrafficPersister:
        class: %cympelAnalytics.routeTrafficPersister.class%
        arguments: [@doctrine]