parameters:
    #Current
    # ** --- The 'ca' namespace contains ALL CympelAnalyticsBundle services
    ## Route Traffic Persister services
    ## ** ** -- The 'rtp' namespace contains ALL RouteTrafficPersister services
    ca.rtp.class:                           Cympel\Bundle\AnalyticsBundle\Services\RouteTrafficPersister
    ## Dynamic CSS services
    ## ** ** -- The 'dcss' namespace contains ALL DynamicCSS services
    ca.dcss.dom_id.manager.class:           Cympel\Bundle\AnalyticsBundle\Services\DynamicCSSDomIdManager
    ca.dcss.dom_id.ac.manager.class:        Cympel\Bundle\AnalyticsBundle\Services\DynamicCSSDomIdArrayCollectionManager
    ca.dcss.extender.class:                 Cympel\Bundle\AnalyticsBundle\Services\DynamicCSSServiceExtension
    ca.dcss.manager.class:                  Cympel\Bundle\AnalyticsBundle\Services\DynamicCSSManager
    ## Dynamic JS services
    ## ** ** -- The 'djs' namespace contains ALL DynamicJS services
    ## ** ** ** -- The 'cds' namespace contains all ClientDataSet services
    ca.djs.cds.dom_classes.creator.class:   Cympel\Bundle\AnalyticsBundle\Services\DynamicJS\DynamicJSSelectorDomEventClientDataSetDomClassesCreator
    ca.djs.extender.class:                  Cympel\Bundle\AnalyticsBundle\Services\DynamicJS\DynamicJSServiceExtension
    ca.djs.dom_event.finder.class:          Cympel\Bundle\AnalyticsBundle\Services\DynamicJS\DynamicJSDomEventFinder
    ca.djs.dom_event.manager.class:         Cympel\Bundle\AnalyticsBundle\Services\DynamicJS\DynamicJSDomEventManager
    ca.djs.dom_events.manager.class:        Cympel\Bundle\AnalyticsBundle\Services\DynamicJS\DynamicJSDomEventsManager
    ca.djs.manager.class:                   Cympel\Bundle\AnalyticsBundle\Services\DynamicJSManager
    ca.djs.selector.manager.class:          Cympel\Bundle\AnalyticsBundle\Services\DynamicJSSelectorManager
    ca.djs.selectors.manager.class:         Cympel\Bundle\AnalyticsBundle\Services\DynamicJS\DynamicJSSelectorsManager
    ## ** ** -- The 'sde' namespace contains all of the SelectorDomEvent services
    ca.djs.sde.finder.class:                Cympel\Bundle\AnalyticsBundle\Services\DynamicJS\DynamicJSSelectorDomEventFinder
    ca.djs.sde.manager.class:               Cympel\Bundle\AnalyticsBundle\Services\DynamicJS\DynamicJSSelectorDomEventManager
    ## Dynamic Tracker services
    ## ** ** -- The 'tracker' namespace contains all Tracker services
    ca.tracker.manager.class:               Cympel\Bundle\AnalyticsBundle\Services\TrackerManager
    ## ** ** ** -- The 'tt' namespace contains all TrackingTool services
    ca.tracker.tt.remover.class:            Cympel\Bundle\AnalyticsBundle\Services\TrackingToolRemover
    ca.tracker.tt.validator.class:          Cympel\Bundle\AnalyticsBundle\Services\TrackingToolValidator
    ## ** -- The 'ns_entities' namespace contains all CympelNamespaceEntities services
    ca.ns_entities.manager.class:           Cympel\Bundle\AnalyticsBundle\Services\CympelNamespaceEntitiesManager
    ca.ns_entities.extender.class:          Cympel\Bundle\AnalyticsBundle\Services\CympelNamespaceEntitiesManagerExtender
    ## ** -- The 'report' namespace contains all services associated with Reporting
    ca.report.runner.class:                 Cympel\Bundle\AnalyticsBundle\Services\ReportRunner


    ### Generics
    ca.generics.persister.class: Cympel\Bundle\AnalyticsBundle\Services\CympelPersister
    cympel_analytics.generics.remover.class: Cympel\Bundle\AnalyticsBundle\Services\CympelRemover
    #cympel_analytics.generics.creatable_registrar.class: Cympel\Bundle\AnalyticsBundle\Services\CreatableRegistrar
    ca.generics.creator.class: Cympel\Bundle\AnalyticsBundle\Services\CympelCreator
    ca.generics.finder.class: Cympel\Bundle\AnalyticsBundle\Services\CympelFinder
    ca.generics.validator.class: Cympel\Bundle\AnalyticsBundle\Services\CympelValidator
    cympel_analytics.generics.router.class: Cympel\Bundle\AnalyticsBundle\Services\CympelRouter
    cympel_analytics.generics.manager.class: Cympel\Bundle\AnalyticsBundle\Services\CympelManager
    ca.generics.namespacer.class: Cympel\Bundle\AnalyticsBundle\Services\CympelNamespacer

    cympel_analytics.entity_manager:
    cympel_analytics.namespace:

services:
    ca.rtp:
        class: %ca.rtp.class%
        arguments: [@doctrine, "%cympel_analytics.entity_manager%"]
    ca.dcss.manager:
        class: %ca.dcss.manager.class%
        arguments: ["@ca.generics.creator", "@ca.generics.finder", "@ca.generics.persister", "@cympel_analytics.generics.remover", "@cympel_analytics.generics.validator", "@ca.dcss.extender"]
    ca.dcss.dom_id.manager:
        class: %ca.dcss.dom_id.manager.class%
        arguments: ["@doctrine", "@validator", "%cympel_analytics.entity_manager%"]
    ca.tracker.manager:
        class: %ca.tracker.manager.class%
        arguments: ["@doctrine", "@ca.tracker.tt.remover", "%cympel_analytics.entity_manager%"]
    ca.djs.manager:
        class: %ca.djs.manager.class%
        arguments: ["@ca.generics.creator", "@ca.generics.finder", "@ca.generics.persister", "@cympel_analytics.generics.remover", "@cympel_analytics.generics.validator", "@ca.djs.extender"]
    ca.dcss.extender:
        class: %ca.dcss.extender.class%
        arguments: ["@ca.dcss.dom_id.manager", "@ca.dcss.dom_id.ac.manager", "@doctrine", "@ca.tracker.tt.remover", "@ca.tracker.tt.validator", "@router", "@ca.tracker.manager", "%cympel_analytics.entity_manager%"]
    ca.dcss.dom_id.ac.manager:
        class: %ca.dcss.dom_id.ac.manager.class%
        arguments: ["@ca.dcss.dom_id.manager", "@ca.generics.creator"]
    ca.tracker.tt.remover:
        class: %ca.tracker.tt.remover.class%
        arguments: ["@doctrine", "@ca.tracker.tt.validator", "%cympel_analytics.entity_manager%", "@ca.generics.namespacer", "%cympel_analytics.namespace%"]
    ca.tracker.tt.validator:
        class: %ca.tracker.tt.validator.class%
        arguments: ["@validator"]
    ca.djs.selector.manager:
        class: %ca.djs.selector.manager.class%
        arguments: ["@ca.generics.creator", "@ca.generics.finder", "@ca.generics.persister", "@cympel_analytics.generics.remover"]
    ca.djs.selectors.manager:
        class: %ca.djs.selectors.manager.class%
        arguments: ["@ca.generics.creator", "@ca.generics.finder", "@ca.generics.persister", "@cympel_analytics.generics.remover", "@cympel_analytics.generics.validator", "@?"]
    ca.djs.extender:
        class: %ca.djs.extender.class%
        arguments: ["@ca.djs.selectors.manager", "@ca.djs.dom_events.manager", "@cympel_analytics.generics.router", "@ca.tracker.manager"]
    ca.djs.dom_events.manager:
        class: %ca.djs.dom_events.manager.class%
        arguments: ["@ca.generics.creator", "@ca.generics.finder", "@ca.generics.persister", "@cympel_analytics.generics.remover", "@cympel_analytics.generics.validator", "@?"]
    ca.djs.dom_event.finder:
        class: %ca.djs.dom_event.finder.class%
        arguments: ["@doctrine", "@cympel_tools.creatable_registrar", "@ca.generics.creator"]
    ca.djs.dom_event.manager:
        class: %ca.djs.dom_event.manager.class%
        arguments: ["@ca.generics.creator", "@ca.djs.dom_event.finder", "@ca.generics.persister", "@cympel_analytics.generics.remover", "@cympel_analytics.generics.validator", "@?"]
    ca.djs.sde.manager:
        class: %ca.djs.sde.manager.class%
        arguments: ["@ca.djs.cds.dom_classes.creator", "@ca.djs.sde.finder", "@ca.generics.persister", "@cympel_analytics.generics.remover", "@cympel_analytics.generics.validator", "@?"]
    ca.djs.sde.finder:
        class: %ca.djs.sde.finder.class%
        arguments: ["@doctrine", "@cympel_tools.creatable_registrar", "@ca.generics.creator"]
    ca.djs.cds.dom_classes.creator:
        class: %ca.djs.cds.dom_classes.creator.class%
        arguments: ["@cympel_tools.creatable_registrar"]
    ca.ns_entities.manager:
        class: %ca.ns_entities.manager.class%
        arguments: ["@ca.generics.creator", "@ca.generics.finder", "@ca.generics.persister", "@cympel_analytics.generics.remover", "@cympel_analytics.generics.validator", "@ca.ns_entities.extender"]
    ca.ns_entities.extender:
        class: %ca.ns_entities.extender.class%
        arguments: []
    ### Report services
    ca.report.runner:
        class: %ca.report.runner.class%
        arguments: ["@ca.generics.creator", "@ca.generics.validator", "@doctrine", "%cympel_analytics.entity_manager%"]
    ### Generics
    ca.generics.persister:
        class: %ca.generics.persister.class%
        arguments: ["@doctrine", "@cympel_analytics.generics.validator", "@ca.generics.namespacer", "%cympel_analytics.namespace%"]
    cympel_analytics.generics.remover:
        class: %cympel_analytics.generics.remover.class%
        arguments: ["@doctrine", "@ca.generics.namespacer", "%cympel_analytics.namespace%"]
    ca.generics.creator:
        class: %ca.generics.creator.class%
        arguments: ["@cympel_tools.creatable_registrar"]
    ca.generics.finder:
        class: %ca.generics.finder.class%
        arguments: ["@doctrine", "@cympel_tools.creatable_registrar", "@ca.generics.creator"]
    ca.generics.validator:
        class: %ca.generics.validator.class%
        arguments: ["@validator"]
    cympel_analytics.generics.router:
        class: %cympel_analytics.generics.router.class%
        arguments: ["@router"]
    cympel_analytics.generics.manager:
        class: %cympel_analytics.generics.manager.class%
        arguments: ["@ca.generics.creator", "@ca.generics.finder", "@ca.generics.persister", "@cympel_analytics.generics.remover", "@cympel_analytics.generics.validator", "@?"]
    ca.generics.namespacer:
        class: %ca.generics.namespacer.class%
        arguments: ["@ca.generics.creator", "@ca.generics.finder", "@ca.ns_entities.extender"]
    #### Service aliases - provided for backwards compatibility
    cympel_analytics.dynamic_css_manager:
        alias: ca.dcss.manager
    cympel_analytics.dynamic_css_dom_id_manager:
        alias: ca.dcss.dom_id.manager
    cympel_analytics.tracker_manager:
        alias: ca.tracker.manager
    cympelAnalytics.routeTrafficPersister:
        alias: ca.rtp
    cympel_analytics.dynamic_js_manager:
        alias: ca.djs.manager
    # @todo write tests of the ca.dcss.extender service
    cympel_analytics.dynamic_css_service_extension:
        alias: ca.dcss.extender
    # @todo write tests of the ca.dcss.dom_id.ac.manager service
    cympel_analytics.dynamic_css_dom_id_array_collection_manager:
        alias: ca.dcss.dom_id.ac.manager
    # @todo write tests of the ca.tracker.tt.remover service
    cympel_analytics.tracking_tool_remover:
        alias: ca.tracker.tt.remover
    # @todo write tests of the ca.tracker.tt.validator service
    cympel_analytics.tracking_tool_validator:
        alias: ca.tracker.tt.validator
    cympel_analytics.dynamic_js_selector_manager:
        alias: ca.djs.selector.manager
    cympel_analytics.dynamic_js_selectors.manager:
        alias: ca.djs.selectors.manager
    cympel_analytics.dynamic_js.extension_service:
        alias: ca.djs.extender
    cympel_analytics.dynamic_js_dom_events.manager:
        alias: ca.djs.dom_events.manager
    cympel_analytics.dynamic_js_dom_event.manager:
        alias: ca.djs.dom_event.manager
    cympel_analytics.dynamic_js_dom_event.finder:
        alias: ca.djs.dom_event.finder
    cympel_analytics.dynamic_js_selector_dom_event.manager:
        alias: ca.djs.sde.manager
    cympel_analytics.dynamic_js_selector_dom_event.finder:
        alias: ca.djs.sde.finder
    cympel_analytics.cds.dom_classes.creator:
        alias: ca.djs.cds.dom_classes.creator
    cympel_analytics.generics.creator:
        alias: ca.generics.creator
    cympel_analytics.generics.persister:
        alias: ca.generics.persister
    cympel_analytics.generics.finder:
        alias: ca.generics.finder
    ### @todo below this line services need to be refactored in services.yml and the AnalyticsBundle
    cympel_analytics.generics.validator:
        alias: ca.generics.validator
