parameters:
    cympelAnalytics.routeTrafficPersister.class: Cympel\Bundle\AnalyticsBundle\Services\RouteTrafficPersister
    cympel_analytics.dynamic_css_manager.class: Cympel\Bundle\AnalyticsBundle\Services\DynamicCSSManager
    cympel_analytics.dynamic_css_dom_id_manager.class: Cympel\Bundle\AnalyticsBundle\Services\DynamicCSSDomIdManager
    cympel_analytics.tracker_manager.class: Cympel\Bundle\AnalyticsBundle\Services\TrackerManager
    cympel_analytics.dynamic_js_manager.class: Cympel\Bundle\AnalyticsBundle\Services\DynamicJSManager
    cympel_analytics.dynamic_css_service_extension.class: Cympel\Bundle\AnalyticsBundle\Services\DynamicCSSServiceExtension
    cympel_analytics.dynamic_css_dom_id_array_collection_manager.class: Cympel\Bundle\AnalyticsBundle\Services\DynamicCSSDomIdArrayCollectionManager
    cympel_analytics.tracking_tool_remover.class: Cympel\Bundle\AnalyticsBundle\Services\TrackingToolRemover
    cympel_analytics.tracking_tool_validator.class: Cympel\Bundle\AnalyticsBundle\Services\TrackingToolValidator
    cympel_analytics.entity_manager:

services:
    cympelAnalytics.routeTrafficPersister:
        class: %cympelAnalytics.routeTrafficPersister.class%
        arguments: [@doctrine, "%cympel_analytics.entity_manager%"]
    cympel_analytics.dynamic_css_manager:
        class: %cympel_analytics.dynamic_css_manager.class%
        arguments: ["@doctrine", "@cympel_analytics.tracking_tool_remover", "@cympel_analytics.tracking_tool_validator", "@router", "@cympel_analytics.tracker_manager", "%cympel_analytics.entity_manager%", "@cympel_analytics.dynamic_css_service_extension"]
    cympel_analytics.dynamic_css_dom_id_manager:
        class: %cympel_analytics.dynamic_css_dom_id_manager.class%
        arguments: ["@doctrine", "@validator", "%cympel_analytics.entity_manager%"]
    cympel_analytics.tracker_manager:
        class: %cympel_analytics.tracker_manager.class%
        arguments: ["@doctrine", "@cympel_analytics.tracking_tool_remover", "%cympel_analytics.entity_manager%"]
    cympel_analytics.dynamic_js_manager:
        class: %cympel_analytics.dynamic_js_manager.class%
        arguments: ["@doctrine", "@cympel_analytics.tracking_tool_remover", "@cympel_analytics.tracking_tool_validator", "@router", "@cympel_analytics.tracker_manager", "%cympel_analytics.entity_manager%"]
    cympel_analytics.dynamic_css_service_extension:
        class: %cympel_analytics.dynamic_css_service_extension.class%
        arguments: ["@cympel_analytics.dynamic_css_dom_id_manager", "@cympel_analytics.dynamic_css_dom_id_array_collection_manager"]
    cympel_analytics.dynamic_css_dom_id_array_collection_manager:
        class: %cympel_analytics.dynamic_css_dom_id_array_collection_manager.class%
        arguments: ["@cympel_analytics.dynamic_css_dom_id_manager"]
    cympel_analytics.tracking_tool_remover:
        class: %cympel_analytics.tracking_tool_remover.class%
        arguments: ["@doctrine", "@cympel_analytics.tracking_tool_validator", "%cympel_analytics.entity_manager%"]
    cympel_analytics.tracking_tool_validator:
        class: %cympel_analytics.tracking_tool_validator.class%
        arguments: ["@validator"]
