parameters:
    cympelAnalytics.routeTrafficPersister.class: Cympel\Bundle\AnalyticsBundle\Services\RouteTrafficPersister
    cympel_analytics.dynamic_css_manager.class: Cympel\Bundle\AnalyticsBundle\Services\DynamicCSSManager
    cympel_analytics.dynamic_css_dom_id_manager.class: Cympel\Bundle\AnalyticsBundle\Services\DynamicCSSDomIdManager
    cympel_analytics.tracker_manager.class: Cympel\Bundle\AnalyticsBundle\Services\TrackerManager
    cympel_analytics.dynamic_js_manager.class: Cympel\Bundle\AnalyticsBundle\Services\DynamicJSManager
    cympel_analytics.dynamic_css_service_extension.class: Cympel\Bundle\AnalyticsBundle\Services\DynamicCSSServiceExtension
    cympel_analytics.dynamic_css_dom_id_array_collection_manager.class: Cympel\Bundle\AnalyticsBundle\Services\DynamicCSSDomIdArrayCollectionManager
    cympel_analytics.tracking_tool_remover.class: Cympel\Bundle\AnalyticsBundle\Services\TrackingToolRemover
    cympel_analytics.tracking_tool_validator.class: Cympel\Bundle\AnalyticsBundle\Services\TrackingToolValidator
    cympel_analytics.dynamic_js_selector_manager.class: Cympel\Bundle\AnalyticsBundle\Services\DynamicJSSelectorManager
    cympel_analytics.dynamic_js_selectors.manager.class: Cympel\Bundle\AnalyticsBundle\Services\DynamicJS\DynamicJSSelectorsManager
    cympel_analytics.dynamic_js.extension_service.class: Cympel\Bundle\AnalyticsBundle\Services\DynamicJS\DynamicJSServiceExtension
    cympel_analytics.dynamic_js_dom_events.manager.class: Cympel\Bundle\AnalyticsBundle\Services\DynamicJS\DynamicJSDomEventsManager
    cympel_analytics.dynamic_js_dom_event.manager.class: Cympel\Bundle\AnalyticsBundle\Services\DynamicJS\DynamicJSDomEventManager
    cympel_analytics.dynamic_js_dom_event.finder.class: Cympel\Bundle\AnalyticsBundle\Services\DynamicJS\DynamicJSDomEventFinder
    cympel_analytics.dynamic_js_selector_dom_event.manager.class: Cympel\Bundle\AnalyticsBundle\Services\DynamicJS\DynamicJSSelectorDomEventManager
    cympel_analytics.dynamic_js_selector_dom_event.finder.class: Cympel\Bundle\AnalyticsBundle\Services\DynamicJS\DynamicJSSelectorDomEventFinder

    ### Creatables
    cympel_analytics.creatables.concrete_persistable_test_type.class: Cympel\Bundle\AnalyticsBundle\Entity\ConcretePersistableTestType
    cympel_analytics.creatables.concrete_persistable_test_type.alias: ConcretePersistableTestType
    cympel_analytics.creatables.concrete_persistable_test_type.entity_manager_name: %cympel_analytics.entity_manager%
    cympel_analytics.creatables.concrete_persistable_test_type.repository_name: CympelAnalyticsBundle:ConcretePersistableTestType

    cympel_analytics.creatables.dynamic_js_selectors.class: Cympel\Bundle\AnalyticsBundle\Entity\DynamicJSSelectors
    cympel_analytics.creatables.dynamic_js_selectors.alias: DynamicJSSelectors
    cympel_analytics.creatables.dynamic_js_selectors.entity_manager_name: %cympel_analytics.entity_manager%
    cympel_analytics.creatables.dynamic_js_selectors.repository_name: CympelAnalyticsBundle:DynamicJSSelectors

    cympel_analytics.creatables.dynamic_js_selector.class: Cympel\Bundle\AnalyticsBundle\Entity\DynamicJSSelector
    cympel_analytics.creatables.dynamic_js_selector.alias: DynamicJSSelector
    cympel_analytics.creatables.dynamic_js_selector.entity_manager_name: %cympel_analytics.entity_manager%
    cympel_analytics.creatables.dynamic_js_selector.repository_name: CympelAnalyticsBundle:DynamicJSSelector

    cympel_analytics.creatables.dynamic_js.class: Cympel\Bundle\AnalyticsBundle\Entity\DynamicJS
    cympel_analytics.creatables.dynamic_js.alias: DynamicJS
    cympel_analytics.creatables.dynamic_js.entity_manager_name: %cympel_analytics.entity_manager%
    cympel_analytics.creatables.dynamic_js.repository_name: CympelAnalyticsBundle:DynamicJS

    cympel_analytics.creatables.dynamic_css.class: Cympel\Bundle\AnalyticsBundle\Entity\DynamicCSS
    cympel_analytics.creatables.dynamic_css.alias: DynamicCSS
    cympel_analytics.creatables.dynamic_css.entity_manager_name: %cympel_analytics.entity_manager%
    cympel_analytics.creatables.dynamic_css.repository_name: CympelAnalyticsBundle:DynamicCSS

    cympel_analytics.creatables.dynamic_js_dom_event.class: Cympel\Bundle\AnalyticsBundle\Entity\DynamicJSDomEvent
    cympel_analytics.creatables.dynamic_js_dom_event.alias: DynamicJSDomEvent
    cympel_analytics.creatables.dynamic_js_dom_event.entity_manager_name: %cympel_analytics.entity_manager%
    cympel_analytics.creatables.dynamic_js_dom_event.repository_name: CympelAnalyticsBundle:DynamicJSDomEvent

    cympel_analytics.creatables.dynamic_js_dom_events.class: Cympel\Bundle\AnalyticsBundle\Entity\DynamicJSDomEvents
    cympel_analytics.creatables.dynamic_js_dom_events.alias: DynamicJSDomEvents
    cympel_analytics.creatables.dynamic_js_dom_events.entity_manager_name: %cympel_analytics.entity_manager%
    cympel_analytics.creatables.dynamic_js_dom_events.repository_name: CympelAnalyticsBundle:DynamicJSDomEvents

    cympel_analytics.creatables.dynamic_js_selector_dom_event.class: Cympel\Bundle\AnalyticsBundle\Entity\DynamicJSSelectorDomEvent
    cympel_analytics.creatables.dynamic_js_selector_dom_event.alias: DynamicJSSelectorDomEvent
    cympel_analytics.creatables.dynamic_js_selector_dom_event.entity_manager_name: %cympel_analytics.entity_manager%
    cympel_analytics.creatables.dynamic_js_selector_dom_event.repository_name: CympelAnalyticsBundle:DynamicJSSelectorDomEvent

    cympel_analytics.creatables.dynamic_js_selector_dom_event_client_data_set.class: Cympel\Bundle\AnalyticsBundle\Entity\DynamicJSSelectorDomEventClientDataSet
    cympel_analytics.creatables.dynamic_js_selector_dom_event_client_data_set.alias: DynamicJSSelectorDomEventClientDataSet
    cympel_analytics.creatables.dynamic_js_selector_dom_event_client_data_set.entity_manager_name: %cympel_analytics.entity_manager%
    cympel_analytics.creatables.dynamic_js_selector_dom_event_client_data_set.repository_name: CympelAnalyticsBundle:DynamicJSSelectorDomEventClientDataSet

    cympel_analytics.creatables.dynamic_js_selector_dom_event_client_data_sets.class: Cympel\Bundle\AnalyticsBundle\Entity\DynamicJSSelectorDomEventClientDataSets
    cympel_analytics.creatables.dynamic_js_selector_dom_event_client_data_sets.alias: DynamicJSSelectorDomEventClientDataSets
    cympel_analytics.creatables.dynamic_js_selector_dom_event_client_data_sets.entity_manager_name: %cympel_analytics.entity_manager%
    cympel_analytics.creatables.dynamic_js_selector_dom_event_client_data_sets.repository_name: CympelAnalyticsBundle:DynamicJSSelectorDomEventClientDataSets

    cympel_analytics.creatables.dynamic_js_selector_dom_event_client_data_set_dom_class.class: Cympel\Bundle\AnalyticsBundle\Entity\DynamicJSSelectorDomEventClientDataSetDomClass
    cympel_analytics.creatables.dynamic_js_selector_dom_event_client_data_set_dom_class.alias: DynamicJSSelectorDomEventClientDataSetDomClass
    cympel_analytics.creatables.dynamic_js_selector_dom_event_client_data_set_dom_class.entity_manager_name: %cympel_analytics.entity_manager%
    cympel_analytics.creatables.dynamic_js_selector_dom_event_client_data_set_dom_class.repository_name: CympelAnalyticsBundle:DynamicJSSelectorDomEventClientDataSetDomClass

    cympel_analytics.creatables.dynamic_js_selector_dom_event_client_data_set_dom_classes.class: Cympel\Bundle\AnalyticsBundle\Entity\DynamicJSSelectorDomEventClientDataSetDomClasses
    cympel_analytics.creatables.dynamic_js_selector_dom_event_client_data_set_dom_classes.alias: DynamicJSSelectorDomEventClientDataSetDomClasses
    cympel_analytics.creatables.dynamic_js_selector_dom_event_client_data_set_dom_classes.entity_manager_name: %cympel_analytics.entity_manager%
    cympel_analytics.creatables.dynamic_js_selector_dom_event_client_data_set_dom_classes.repository_name: CympelAnalyticsBundle:DynamicJSSelectorDomEventClientDataSetDomClasses

    ### Generics
    cympel_analytics.generics.persister.class: Cympel\Bundle\AnalyticsBundle\Services\CympelPersister
    cympel_analytics.generics.remover.class: Cympel\Bundle\AnalyticsBundle\Services\CympelRemover
    cympel_analytics.generics.creatable_registrar.class: Cympel\Bundle\AnalyticsBundle\Services\CreatableRegistrar
    cympel_analytics.generics.creator.class: Cympel\Bundle\AnalyticsBundle\Services\CympelCreator
    cympel_analytics.generics.finder.class: Cympel\Bundle\AnalyticsBundle\Services\CympelFinder
    cympel_analytics.generics.validator.class: Cympel\Bundle\AnalyticsBundle\Services\CympelValidator
    cympel_analytics.generics.router.class: Cympel\Bundle\AnalyticsBundle\Services\CympelRouter
    cympel_analytics.generics.manager.class: Cympel\Bundle\AnalyticsBundle\Services\CympelManager
    cympel_analytics.entity_manager:

services:
    cympelAnalytics.routeTrafficPersister:
        class: %cympelAnalytics.routeTrafficPersister.class%
        arguments: [@doctrine, "%cympel_analytics.entity_manager%"]
    cympel_analytics.dynamic_css_manager:
        class: %cympel_analytics.dynamic_css_manager.class%
        arguments: ["@cympel_analytics.generics.creator", "@cympel_analytics.generics.finder", "@cympel_analytics.generics.persister", "@cympel_analytics.generics.remover", "@cympel_analytics.generics.validator", "@cympel_analytics.dynamic_css_service_extension"]
    cympel_analytics.dynamic_css_dom_id_manager:
        class: %cympel_analytics.dynamic_css_dom_id_manager.class%
        arguments: ["@doctrine", "@validator", "%cympel_analytics.entity_manager%"]
    cympel_analytics.tracker_manager:
        class: %cympel_analytics.tracker_manager.class%
        arguments: ["@doctrine", "@cympel_analytics.tracking_tool_remover", "%cympel_analytics.entity_manager%"]
    cympel_analytics.dynamic_js_manager:
        class: %cympel_analytics.dynamic_js_manager.class%
        arguments: ["@cympel_analytics.generics.creator", "@cympel_analytics.generics.finder", "@cympel_analytics.generics.persister", "@cympel_analytics.generics.remover", "@cympel_analytics.generics.validator", "@cympel_analytics.dynamic_js.extension_service"]
    cympel_analytics.dynamic_css_service_extension:
        class: %cympel_analytics.dynamic_css_service_extension.class%
        arguments: ["@cympel_analytics.dynamic_css_dom_id_manager", "@cympel_analytics.dynamic_css_dom_id_array_collection_manager", "@doctrine", "@cympel_analytics.tracking_tool_remover", "@cympel_analytics.tracking_tool_validator", "@router", "@cympel_analytics.tracker_manager", "%cympel_analytics.entity_manager%"]
    cympel_analytics.dynamic_css_dom_id_array_collection_manager:
        class: %cympel_analytics.dynamic_css_dom_id_array_collection_manager.class%
        arguments: ["@cympel_analytics.dynamic_css_dom_id_manager"]
    cympel_analytics.tracking_tool_remover:
        class: %cympel_analytics.tracking_tool_remover.class%
        arguments: ["@doctrine", "@cympel_analytics.tracking_tool_validator", "%cympel_analytics.entity_manager%"]
    cympel_analytics.tracking_tool_validator:
        class: %cympel_analytics.tracking_tool_validator.class%
        arguments: ["@validator"]
    cympel_analytics.dynamic_js_selector_manager:
        class: %cympel_analytics.dynamic_js_selector_manager.class%
        arguments: ["@cympel_analytics.generics.creator", "@cympel_analytics.generics.finder", "@cympel_analytics.generics.persister", "@cympel_analytics.generics.remover"]
    cympel_analytics.dynamic_js_selectors.manager:
        class: %cympel_analytics.dynamic_js_selectors.manager.class%
        arguments: ["@cympel_analytics.generics.creator", "@cympel_analytics.generics.finder", "@cympel_analytics.generics.persister", "@cympel_analytics.generics.remover", "@cympel_analytics.generics.validator", "@?"]
    cympel_analytics.dynamic_js.extension_service:
        class: %cympel_analytics.dynamic_js.extension_service.class%
        arguments: ["@cympel_analytics.dynamic_js_selectors.manager", "@cympel_analytics.dynamic_js_dom_events.manager", "@cympel_analytics.generics.router", "@cympel_analytics.tracker_manager"]
    cympel_analytics.dynamic_js_dom_events.manager:
        class: %cympel_analytics.dynamic_js_dom_events.manager.class%
        arguments: ["@cympel_analytics.generics.creator", "@cympel_analytics.generics.finder", "@cympel_analytics.generics.persister", "@cympel_analytics.generics.remover", "@cympel_analytics.generics.validator", "@?"]
    cympel_analytics.dynamic_js_dom_event.finder:
        class: %cympel_analytics.dynamic_js_dom_event.finder.class%
        arguments: ["@doctrine", "@cympel_analytics.generics.creatable_registrar", "@cympel_analytics.generics.creator"]
    cympel_analytics.dynamic_js_dom_event.manager:
        class: %cympel_analytics.dynamic_js_dom_event.manager.class%
        arguments: ["@cympel_analytics.generics.creator", "@cympel_analytics.dynamic_js_dom_event.finder", "@cympel_analytics.generics.persister", "@cympel_analytics.generics.remover", "@cympel_analytics.generics.validator", "@?"]
    cympel_analytics.dynamic_js_selector_dom_event.manager:
        class: %cympel_analytics.dynamic_js_selector_dom_event.manager.class%
        arguments: ["@cympel_analytics.generics.creator", "@cympel_analytics.dynamic_js_selector_dom_event.finder", "@cympel_analytics.generics.persister", "@cympel_analytics.generics.remover", "@cympel_analytics.generics.validator", "@?"]
    cympel_analytics.dynamic_js_selector_dom_event.finder:
        class: %cympel_analytics.dynamic_js_selector_dom_event.finder.class%
        arguments: ["@doctrine", "@cympel_analytics.generics.creatable_registrar", "@cympel_analytics.generics.creator"]
   ### Generics
    cympel_analytics.generics.persister:
        class: %cympel_analytics.generics.persister.class%
        arguments: ["@doctrine", "@cympel_analytics.generics.validator"]
    cympel_analytics.generics.remover:
        class: %cympel_analytics.generics.remover.class%
        arguments: ["@doctrine"]
    cympel_analytics.generics.creatable_registrar:
        class: %cympel_analytics.generics.creatable_registrar.class%
        calls:
            - [register, ["%cympel_analytics.creatables.concrete_persistable_test_type.class%", "%cympel_analytics.creatables.concrete_persistable_test_type.alias%", "%cympel_analytics.creatables.concrete_persistable_test_type.repository_name%", "%cympel_analytics.creatables.concrete_persistable_test_type.entity_manager_name%"]]
            - [register, ["%cympel_analytics.creatables.dynamic_js_selectors.class%", "%cympel_analytics.creatables.dynamic_js_selectors.alias%", "%cympel_analytics.creatables.dynamic_js_selectors.repository_name%", "%cympel_analytics.creatables.dynamic_js_selectors.entity_manager_name%"]]
            - [register, ["%cympel_analytics.creatables.dynamic_js_selector.class%", "%cympel_analytics.creatables.dynamic_js_selector.alias%", "%cympel_analytics.creatables.dynamic_js_selector.repository_name%", "%cympel_analytics.creatables.dynamic_js_selector.entity_manager_name%"]]
            - [register, ["%cympel_analytics.creatables.dynamic_js.class%", "%cympel_analytics.creatables.dynamic_js.alias%", "%cympel_analytics.creatables.dynamic_js.repository_name%", "%cympel_analytics.creatables.dynamic_js.entity_manager_name%"]]
            - [register, ["%cympel_analytics.creatables.dynamic_css.class%", "%cympel_analytics.creatables.dynamic_css.alias%", "%cympel_analytics.creatables.dynamic_css.repository_name%", "%cympel_analytics.creatables.dynamic_css.entity_manager_name%"]]
            - [register, ["%cympel_analytics.creatables.dynamic_js_dom_event.class%", "%cympel_analytics.creatables.dynamic_js_dom_event.alias%", "%cympel_analytics.creatables.dynamic_js_dom_event.repository_name%", "%cympel_analytics.creatables.dynamic_js_dom_event.entity_manager_name%"]]
            - [register, ["%cympel_analytics.creatables.dynamic_js_dom_events.class%", "%cympel_analytics.creatables.dynamic_js_dom_events.alias%", "%cympel_analytics.creatables.dynamic_js_dom_events.repository_name%", "%cympel_analytics.creatables.dynamic_js_dom_events.entity_manager_name%"]]
            - [register, ["%cympel_analytics.creatables.dynamic_js_selector_dom_event.class%", "%cympel_analytics.creatables.dynamic_js_selector_dom_event.alias%", "%cympel_analytics.creatables.dynamic_js_selector_dom_event.repository_name%", "%cympel_analytics.creatables.dynamic_js_selector_dom_event.entity_manager_name%"]]
            - [register, ["%cympel_analytics.creatables.dynamic_js_selector_dom_event_client_data_set.class%", "%cympel_analytics.creatables.dynamic_js_selector_dom_event_client_data_set.alias%", "%cympel_analytics.creatables.dynamic_js_selector_dom_event_client_data_set.repository_name%", "%cympel_analytics.creatables.dynamic_js_selector_dom_event_client_data_set.entity_manager_name%"]]
            - [register, ["%cympel_analytics.creatables.dynamic_js_selector_dom_event_client_data_sets.class%", "%cympel_analytics.creatables.dynamic_js_selector_dom_event_client_data_sets.alias%", "%cympel_analytics.creatables.dynamic_js_selector_dom_event_client_data_sets.repository_name%", "%cympel_analytics.creatables.dynamic_js_selector_dom_event_client_data_sets.entity_manager_name%"]]
            - [register, ["%cympel_analytics.creatables.dynamic_js_selector_dom_event_client_data_set_dom_class.class%", "%cympel_analytics.creatables.dynamic_js_selector_dom_event_client_data_set_dom_class.alias%", "%cympel_analytics.creatables.dynamic_js_selector_dom_event_client_data_set_dom_class.repository_name%", "%cympel_analytics.creatables.dynamic_js_selector_dom_event_client_data_set_dom_class.entity_manager_name%"]]
            - [register, ["%cympel_analytics.creatables.dynamic_js_selector_dom_event_client_data_set_dom_classes.class%", "%cympel_analytics.creatables.dynamic_js_selector_dom_event_client_data_set_dom_classes.alias%", "%cympel_analytics.creatables.dynamic_js_selector_dom_event_client_data_set_dom_classes.repository_name%", "%cympel_analytics.creatables.dynamic_js_selector_dom_event_client_data_set_dom_classes.entity_manager_name%"]]
    cympel_analytics.generics.creator:
        class: %cympel_analytics.generics.creator.class%
        arguments: ["@cympel_analytics.generics.creatable_registrar"]
    cympel_analytics.generics.finder:
        class: %cympel_analytics.generics.finder.class%
        arguments: ["@doctrine", "@cympel_analytics.generics.creatable_registrar", "@cympel_analytics.generics.creator"]
    cympel_analytics.generics.validator:
        class: %cympel_analytics.generics.validator.class%
        arguments: ["@validator"]
    cympel_analytics.generics.router:
        class: %cympel_analytics.generics.router.class%
        arguments: ["@router"]
    cympel_analytics.generics.manager:
        class: %cympel_analytics.generics.manager.class%
        arguments: ["@cympel_analytics.generics.creator", "@cympel_analytics.generics.finder", "@cympel_analytics.generics.persister", "@cympel_analytics.generics.remover", "@cympel_analytics.generics.validator", "@?"]
