parameters:
    cympelAnalytics.routeTrafficPersister.class: Cympel\Bundle\AnalyticsBundle\Services\RouteTrafficPersister
    cympel_analytics.dynamic_css_manager.class: Cympel\Bundle\AnalyticsBundle\Services\DynamicCSSManager
    cympel_analytics.dynamic_css_dom_id_manager.class: Cympel\Bundle\AnalyticsBundle\Services\DynamicCSSDomIdManager
    cympel_analytics.tracker_manager.class: Cympel\Bundle\AnalyticsBundle\Services\TrackerManager
    cympel_analytics.dynamic_js_manager.class: Cympel\Bundle\AnalyticsBundle\Services\DynamicJSManager
    cympel_analytics.dynamic_css_service_extension.class: Cympel\Bundle\AnalyticsBundle\Services\DynamicCSSServiceExtension
    cympel_analytics.dynamic_css_dom_id_array_collection_manager.class: Cympel\Bundle\AnalyticsBundle\Services\DynamicCSSDomIdArrayCollectionManager
    cympel_analytics.tracking_tool_remover.class: Cympel\Bundle\AnalyticsBundle\Services\TrackingToolRemover
    cympel_analytics.tracking_tool_validator.class: Cympel\Bundle\AnalyticsBundle\Services\TrackingToolValidator
    cympel_analytics.dynamic_js_selector_manager.class: Cympel\Bundle\AnalyticsBundle\Services\DynamicJSSelectorManager
    cympel_analytics.dynamic_js_selectors.manager.class: Cympel\Bundle\AnalyticsBundle\Services\DynamicJS\DynamicJSSelectorsManager

    ### Creatables
    cympel_analytics.creatables.concrete_persistable_test_type.class: Cympel\Bundle\AnalyticsBundle\Entity\ConcretePersistableTestType
    cympel_analytics.creatables.concrete_persistable_test_type.alias: ConcretePersistableTestType
    cympel_analytics.creatables.concrete_persistable_test_type.entity_manager_name: %cympel_analytics.entity_manager%
    cympel_analytics.creatables.concrete_persistable_test_type.repository_name: CympelAnalyticsBundle:ConcretePersistableTestType

    cympel_analytics.creatables.dynamic_js_selectors.class: Cympel\Bundle\AnalyticsBundle\Entity\DynamicJSSelectors
    cympel_analytics.creatables.dynamic_js_selectors.alias: DynamicJSSelectors
    cympel_analytics.creatables.dynamic_js_selectors.entity_manager_name: %cympel_analytics.entity_manager%
    cympel_analytics.creatables.dynamic_js_selectors.repository_name: CympelAnalyticsBundle:DynamicJSSelectors

    cympel_analytics.creatables.dynamic_js_selector.class: Cympel\Bundle\AnalyticsBundle\Entity\DynamicJSSelector
    cympel_analytics.creatables.dynamic_js_selector.alias: DynamicJSSelector
    cympel_analytics.creatables.dynamic_js_selector.entity_manager_name: %cympel_analytics.entity_manager%
    cympel_analytics.creatables.dynamic_js_selector.repository_name: CympelAnalyticsBundle:DynamicJSSelector

    cympel_analytics.creatables.dynamic_js.class: Cympel\Bundle\AnalyticsBundle\Entity\DynamicJS
    cympel_analytics.creatables.dynamic_js.alias: DynamicJS
    cympel_analytics.creatables.dynamic_js.entity_manager_name: %cympel_analytics.entity_manager%
    cympel_analytics.creatables.dynamic_js.repository_name: CympelAnalyticsBundle:DynamicJS

    cympel_analytics.creatables.dynamic_css.class: Cympel\Bundle\AnalyticsBundle\Entity\DynamicCSS
    cympel_analytics.creatables.dynamic_css.alias: DynamicCSS
    cympel_analytics.creatables.dynamic_css.entity_manager_name: %cympel_analytics.entity_manager%
    cympel_analytics.creatables.dynamic_css.repository_name: CympelAnalyticsBundle:DynamicCSS

    ### Generics
    cympel_analytics.generics.persister.class: Cympel\Bundle\AnalyticsBundle\Services\CympelPersister
    cympel_analytics.generics.remover.class: Cympel\Bundle\AnalyticsBundle\Services\CympelRemover
    cympel_analytics.generics.creatable_registrar.class: Cympel\Bundle\AnalyticsBundle\Services\CreatableRegistrar
    cympel_analytics.generics.creator.class: Cympel\Bundle\AnalyticsBundle\Services\CympelCreator
    cympel_analytics.generics.finder.class: Cympel\Bundle\AnalyticsBundle\Services\CympelFinder
    cympel_analytics.entity_manager:

services:
    cympelAnalytics.routeTrafficPersister:
        class: %cympelAnalytics.routeTrafficPersister.class%
        arguments: [@doctrine, "%cympel_analytics.entity_manager%"]
    cympel_analytics.dynamic_css_manager:
        class: %cympel_analytics.dynamic_css_manager.class%
        arguments: ["@cympel_analytics.generics.finder", "@cympel_analytics.generics.creator", "@doctrine", "@cympel_analytics.tracking_tool_remover", "@cympel_analytics.tracking_tool_validator", "@router", "@cympel_analytics.tracker_manager", "%cympel_analytics.entity_manager%", "@cympel_analytics.dynamic_css_service_extension"]
    cympel_analytics.dynamic_css_dom_id_manager:
        class: %cympel_analytics.dynamic_css_dom_id_manager.class%
        arguments: ["@doctrine", "@validator", "%cympel_analytics.entity_manager%"]
    cympel_analytics.tracker_manager:
        class: %cympel_analytics.tracker_manager.class%
        arguments: ["@doctrine", "@cympel_analytics.tracking_tool_remover", "%cympel_analytics.entity_manager%"]
    cympel_analytics.dynamic_js_manager:
        class: %cympel_analytics.dynamic_js_manager.class%
        arguments: ["@cympel_analytics.generics.finder", "@cympel_analytics.generics.creator", "@doctrine", "@cympel_analytics.tracking_tool_remover", "@cympel_analytics.tracking_tool_validator", "@router", "@cympel_analytics.tracker_manager", "%cympel_analytics.entity_manager%"]
    cympel_analytics.dynamic_css_service_extension:
        class: %cympel_analytics.dynamic_css_service_extension.class%
        arguments: ["@cympel_analytics.dynamic_css_dom_id_manager", "@cympel_analytics.dynamic_css_dom_id_array_collection_manager"]
    cympel_analytics.dynamic_css_dom_id_array_collection_manager:
        class: %cympel_analytics.dynamic_css_dom_id_array_collection_manager.class%
        arguments: ["@cympel_analytics.dynamic_css_dom_id_manager"]
    cympel_analytics.tracking_tool_remover:
        class: %cympel_analytics.tracking_tool_remover.class%
        arguments: ["@doctrine", "@cympel_analytics.tracking_tool_validator", "%cympel_analytics.entity_manager%"]
    cympel_analytics.tracking_tool_validator:
        class: %cympel_analytics.tracking_tool_validator.class%
        arguments: ["@validator"]
    cympel_analytics.dynamic_js_selector_manager:
        class: %cympel_analytics.dynamic_js_selector_manager.class%
        arguments: ["@cympel_analytics.generics.creator", "@cympel_analytics.generics.finder", "@cympel_analytics.generics.persister", "@cympel_analytics.generics.remover"]
    cympel_analytics.dynamic_js_selectors.manager:
        class: %cympel_analytics.dynamic_js_selectors.manager.class%
        arguments: ["@cympel_analytics.generics.creator", "@cympel_analytics.generics.finder", "@cympel_analytics.generics.persister", "@cympel_analytics.generics.remover"]
   ### Generics
    cympel_analytics.generics.persister:
        class: %cympel_analytics.generics.persister.class%
        arguments: ["@doctrine"]
    cympel_analytics.generics.remover:
        class: %cympel_analytics.generics.remover.class%
        arguments: ["@doctrine"]
    cympel_analytics.generics.creatable_registrar:
        class: %cympel_analytics.generics.creatable_registrar.class%
        calls:
            - [register, ["%cympel_analytics.creatables.concrete_persistable_test_type.class%", "%cympel_analytics.creatables.concrete_persistable_test_type.alias%", "%cympel_analytics.creatables.concrete_persistable_test_type.repository_name%", "%cympel_analytics.creatables.concrete_persistable_test_type.entity_manager_name%"]]
            - [register, ["%cympel_analytics.creatables.dynamic_js_selectors.class%", "%cympel_analytics.creatables.dynamic_js_selectors.alias%", "%cympel_analytics.creatables.dynamic_js_selectors.repository_name%", "%cympel_analytics.creatables.dynamic_js_selectors.entity_manager_name%"]]
            - [register, ["%cympel_analytics.creatables.dynamic_js_selector.class%", "%cympel_analytics.creatables.dynamic_js_selector.alias%", "%cympel_analytics.creatables.dynamic_js_selector.repository_name%", "%cympel_analytics.creatables.dynamic_js_selector.entity_manager_name%"]]
            - [register, ["%cympel_analytics.creatables.dynamic_js.class%", "%cympel_analytics.creatables.dynamic_js.alias%", "%cympel_analytics.creatables.dynamic_js.repository_name%", "%cympel_analytics.creatables.dynamic_js.entity_manager_name%"]]
            - [register, ["%cympel_analytics.creatables.dynamic_css.class%", "%cympel_analytics.creatables.dynamic_css.alias%", "%cympel_analytics.creatables.dynamic_css.repository_name%", "%cympel_analytics.creatables.dynamic_css.entity_manager_name%"]]
    cympel_analytics.generics.creator:
        class: %cympel_analytics.generics.creator.class%
        arguments: ["@cympel_analytics.generics.creatable_registrar"]
    cympel_analytics.generics.finder:
        class: %cympel_analytics.generics.finder.class%
        arguments: ["@doctrine", "@cympel_analytics.generics.creatable_registrar", "@cympel_analytics.generics.creator"]
